#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'chef-client'
cookbook 'chef-vault'
cookbook 'sudo'
cookbook 'user'

cookbook 'madalynn',
  :git => 'https://github.com/androirc/chef-madalynn.git'
